Use CpabilityStatement.instantiates
gematik/ISiK-Basismodul-Stufe-2 pull request #100
Opened 2022-03-10 09:58 UTC by alexzautke

2022-03-11 09:51 UTC, ylboerner requested changes

2022-03-11 09:51 UTC, ylboerner commented on Resources/fsh-generated/resources/Composition-composition-blutdruck.json
> +    "reference": "encounter"
Woher kommen diese Änderungen? Falls unklar, bitte entfernen 👍

2022-03-18 10:57 UTC, alexzautke commented on Resources/fsh-generated/resources/Composition-composition-blutdruck.json
> +    "reference": "encounter"
Kommt aus einer Änderung die bereits im Master ist, ich mach ein separates Issue auf

2022-03-18 11:34 UTC, alexzautke commented on Resources/fsh-generated/resources/Composition-composition-blutdruck.json
> +    "reference": "encounter"
Siehe https://github.com/gematik/ISiK-Basismodul-Stufe-2/issues/109

2022-03-18 11:45 UTC, ylboerner approved these changes

2022-03-18 11:45 UTC, merged