feature: Add best practice für Standardsuchfilter
gematik/ISiK-Basismodul-Stufe-2 pull request #33
Opened 2021-12-27 18:32 UTC by ylboerner

2022-01-06 12:56 UTC, ylboerner commented on ImplementationGuide/UebergreifendeFestlegungen_Suchparameter.md
> +- Der Server berücksichtigt bei Suchvorgängen Parameter mit fehlenden Werten und sendet bei fehlerhaften Suchparametern eine geeignete Antwort an den Client.
Link zur Spec bezüglich fehlenden Suchparametern

2022-01-06 12:57 UTC, ylboerner commented on ImplementationGuide/UebergreifendeFestlegungen_Suchparameter.md
> +- Der Server sorgt dafür, dass Clients die benötigten Informationen finden können, auch bei Inhalten, die sich über mehrere FHIR-Ressourcen hinweg strecken.
"Sollte"

2022-01-13 16:18 UTC, alexzautke requested changes

2022-01-13 16:18 UTC, alexzautke commented on ImplementationGuide/UebergreifendeFestlegungen_Suchparameter.md
> +Diese grundlegenden Best Practice Empfehlungen beziehen sich auf die korrekte Verwaltung des Suchprozesses seitens des Servers mit Bezug auf Sicherheit im klinischen Umfeld. Unstimmigkeiten in den Er
Im *Folgenden* (Typo, großes F)

2022-01-13 16:18 UTC, alexzautke commented on ImplementationGuide/UebergreifendeFestlegungen_Suchparameter.md
> +- Der Server sollte dafür sorgen, dass Clients die benötigten Informationen finden können, auch bei Inhalten, die sich über mehrere FHIR-Ressourcen hinweg strecken.
SOLLTE anstatt sollte

2022-01-13 16:18 UTC, alexzautke commented on ImplementationGuide/UebergreifendeFestlegungen_Suchparameter.md
> +- Wenn der Inhalt eines Suchparameters leer ist, sollte der Server diesen ignorieren.
Verweis auf https://www.hl7.org/fhir/search.html#errors + Ticket in ISiK Testing erstellen, falls noch nicht vorhanden

2022-01-14 14:29 UTC, alexzautke approved these changes

2022-01-14 14:39 UTC, merged